---
    - name: prepare squid config file
      template: src=templates/squid.conf.j2 dest=/etc/squid/squid.conf owner=root group=squid mode=0644
      notify: 
      - restart_squid

    - name: replace a customized logo and error page
      copy: src={{ item.src }} dest=/usr/share/squid/{{ item.dest }} owner=root group=root mode=0644
      with_items:
      - { src: SN.png, dest: icons/SN.png }
      - { src: ERR_ACCESS_DENIED, dest: errors/ERR_ACCESS_DENIED }
      notify:
      - restart_squid

    - name: configure /etc/squid/conf.d directory
      file: path=/etc/squid/conf.d state=directory mode=0755 owner=root group=squid
      notify: 
      - restart_squid

    - name: configure /etc/squid/lists directory
      file: path=/etc/squid/lists state=directory mode=0755 owner=root group=squid
      notify: 
      - restart_squid

    - name: configure c-icap integration
      copy: src=files/99.c-icap-integration.conf dest=/etc/squid/conf.d/99.c-icap-integration.conf owner=root group=squid mode=0644
      when: enable_antivirus
      notify: 
      - restart_squid

    - name: disable c-icap integration
      file: path=/etc/squid/conf.d/99.c-icap-integration.conf state=absent
      when: disable_antivirus
      notify: 
      - restart_squid

    - name: configure ldapacl file
      copy: dest=/etc/squid/conf.d/10.ldapacl.conf src=files/{{ uuid_file_name }} owner=root group=squid mode=0644
      when: add_ldapacl
      notify: 
      - restart_squid
      tags:
      - update_ldap_acl

    - name: remove ldapacl file 
      file: path=/etc/squid/conf.d/10.ldapacl.conf state=absent
      when: remove_ldapacl
      notify:
      - restart_squid 

#    - name: configure list files
#      copy: dest=/etc/squid/lists/{{ item }} src=files/{{ item }}
#      with_items:
#        - list1.list
#        - list2.list
#
#    - name: configure list files
#      copy: src={{ item }} dest=/etc/squid/lists/  owner=root group=squid mode=0644
#      with_fileglob:
#        - files/{{ uuid_name }}
#      notify: 
#      - restart_squid

    - name: disable dansguardian
      shell:  chkconfig dansguardian off

    - name: disable dansguardian
      shell: service dansguardian stop

#    - name: restarting squid
#      service: name=squid state=restarted enabled=yes
