---
    - name: prepare squid config file
      template: src=templates/squid.conf.j2 dest=/etc/squid/squid.conf owner=root group=squid mode=0644

    - name: configure /etc/squid/conf.d directory
      file: path=/etc/squid/conf.d state=directory mode=0755 owner=root group=squid

    - name: configure /etc/squid/lists directory
      file: path=/etc/squid/lists state=directory mode=0755 owner=root group=squid

    - name: configure c-icap integration
      copy: src=files/99.c-icap-integration.conf dest=/etc/squid/conf.d/99.c-icap-integration.conf owner=root group=squid mode=0644

    - name: disable c-icap integration
      file: path=/etc/squid/conf.d/99.c-icap-integration.conf state=absent
      when: disable_antivirus

    - name: configure ldapacl file
      copy: dest=/etc/squid/conf.d/10.ldapacl.conf src=files/10.ldapacl.conf owner=root group=squid mode=0644

    - name: configure list files
      copy: dest=/etc/squid/lists/{{ item }} src=files/{{ item }}
      with_items:
        - list1.list
        - list2.list

    - name: disable dansguardian
      shell:  chkconfig dansguardian off

    - name: disable dansguardian
      shell: service dansguardian stop

    - name: restarting squid
      service: name=squid state=restarted enabled=yes
